Fixed color; Cleaner Resolution display

diff --git a/kimfetch/kimfetch b/kimfetch/kimfetch
--- a/kimfetch/kimfetch
+++ b/kimfetch/kimfetch
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # *** Kimfetch ***
-# Version 1.0 
+# Version 1.1 
 # By Jiayuan "Weldon" Wen
 # Licence: CC BY-NC 4.0, more info: https://creativecommons.org/licenses/by-nc/4.0/?ref=chooser-v1
 
@@ -10,15 +10,25 @@
 # Since Red Star OS is missing the ability to implement functions in custom scripts, please avoid functions when modifying this script.
 # Warning: Red Star OS is developed by the DPRK, it is highly adviced not to install the system on your machine due to privacy risk and for personal safity. If you must use the OS, please install in a virtual environment with no access to internet. 
 
-# === Header ===
-# "Username@Hostname" as displayed on terminal
-SESSION="\e[1;31m$(whoami)\e[0m@\e[1;31m$(hostname)\e[0m";
+# Flags
+while getopts c:hf flag
+do
+	case "${flag}" in
+		c) color_code=${OPTARG};;
+		f) default_color=true;;
+		h) display_help=true;;
+	esac
+done
 
-# === Separation line below header ===
-SEP=""
-LOOP="${#SESSION}"
-LOOP=$(($LOOP-16-10)) # Do not count color codes. Remove two "\e[1;31m" and two "\e[0m"
-SEP=$(printf "%0.s-" $(seq 1 $LOOP))
+# Display help when user state -h flag
+if [[ -n "$display_help" ]] && [ "$display_help" == true ]; then
+	echo "Flags:"
+    echo "  -c    Set color theme (1: Red, 2: Green). Usage: kimfetch -c [int]"
+	echo "  -f    Cancel set color theme and use default. Usage: kimfetch -f"
+    echo "  -h    Display help. Usage: kimfetch -h"
+	
+	exit 0;
+fi
 
 # === OS info ===
 # Credit: kvivek & Peter Mortensen from StackOverflow
@@ -64,9 +74,12 @@ fi
 OS=${OSSTR}
 
 # === System board name ===
-BOARD=""
-BOARD+=`cat /sys/devices/virtual/dmi/id/board_vendor`" "`cat /sys/devices/virtual/dmi/id/board_name`" "`cat /sys/devices/virtual/dmi/id/board_version`
-
+if [ -e "/sys/devices/virtual/dmi/id/board_vendor" ]; then
+	BOARD=""
+	BOARD+=`cat /sys/devices/virtual/dmi/id/board_vendor`" "`cat /sys/devices/virtual/dmi/id/board_name`" "`cat /sys/devices/virtual/dmi/id/board_version`
+else
+	BOARD="Inapplicable"
+fi
 # === Kernel name ===
 KERNEL=`uname -r`
 
@@ -94,13 +107,44 @@ else
 fi
 
 # === Screen resolution ===
-SCREEN="$(echo $(xrandr | fgrep "*"))" # Wrapped in echo to eliminate unnecessary spaces
+SCREEN=""
+FPS=""
+if command -v "xrandr" > /dev/null; then
+#if ! command -v "xrandr" > /dev/null; then #For debug use
+
+	# xrandr gives un-suppressible warning messages,
+	# Load everything into a file with &>, then grep what's needed.
+	MONITOR=$(mktemp)
+	xrandr &> $MONITOR
+	#echo "1920x1080 0.0*" &> $MONITOR #For debug use
+	
+	# tr shrink all spaces to one to remove unnecessary spaces
+	# sed to remove "*"
+	MONITOR=$(cat $MONITOR | fgrep "*" | tr -s ' ' | sed 's/\*//') 
+	
+	# sed regex to separate resolution and refresh rate
+	# Note to self: for regex quantifier in sed(*,?,+), escape with "\"
+	SCREEN="$(echo $MONITOR | sed 's/\ [0-9]\?[0-9]\?[0-9]\.[0-9][0-9]\?[0-9]\?//')" 
+	FPS="$(echo $MONITOR | sed 's/[0-9]\?[0-9]\?[0-9]\?[0-9]x[0-9][0-9]\?[0-9]\?[0-9]\?\ //')Hz"
+	
+	# If xrandr can't read refresh rate, leave it blank
+	if [ "$FPS" == "0.0Hz" ]; then
+		FPS=""
+	fi
+else
+	SCREEN="Inapplicable"
+fi
+
 
 # === Desktop Environment ===
 # We know Red Star OS 2.0 and 3.0 use KDE as DE according to https://archiveos.org/redstar/
-DE=$(konsole --version | grep "KDE")
-DE=${DE//[:]/ }
-DE=$(echo $DE) # Eliminate unnecessary spaces
+if command -v "konsole" > /dev/null; then
+	DE=$(konsole --version | grep "KDE")
+	DE=${DE//[:]/ }
+	DE=$(echo $DE) # Eliminate unnecessary spaces
+else
+	DE="Inapplicable"
+fi
 
 # === Window Manager ===
 WM=""
@@ -120,8 +164,12 @@ CPU=$(cat /proc/cpuinfo | grep "model name" | head -1)
 CPU="$(echo ${CPU#*:})"
 
 # === GPU name ===
-GPU=$(lspci | grep "VGA" | head -1)
-GPU="$(echo ${GPU#*:*:})"
+if [ -d "/proc/bus/pci" ]; then
+	GPU=$(lspci | grep "VGA" | head -1)
+	GPU="$(echo ${GPU#*:*:})"
+else
+	GPU="Inapplicable"
+fi
 
 # === Memory usage ===
 MEM_USED=$(free -m | awk 'FNR == 2 {print $3}')
@@ -136,23 +184,99 @@ STO_PERC=$(df -h / | awk 'FNR == 2 {print $5}' | tr -d \%);
 #STO=$(printf "%s" "${STO_USED}B / ${STO_TOTAL}B ($(echo ${STO_PERC}))")
 STO=$(printf "%s" "${STO_USED}B / ${STO_TOTAL}B")
 
+# === Color ===
+COLOR=""
+CFG_DIR="$HOME/.config/kimfetch"
+# Check if config folder exist
+if [ -d "$CFG_DIR" ]; then
+	true
+	#echo "Config folder exist"
+else
+	mkdir "$CFG_DIR"
+	#echo "Config folder not exist"
+fi
+# If user set a color with the -c flag
+if [[ -n "$color_code" ]]; then
+	# Make sure user is not running as root
+	if [ "$EUID" -eq 0 ]; then
+		echo "Error: Must run as non-root"
+		newline
+		exit 1
+	fi
+	# Check if user set valid value
+	if [ "$color_code" == "1" ] || [ "$color_code" == "2" ]; then
+		if [ ! -f "$HOME/.config/kimfetch/color" ]; then
+			touch "$HOME/.config/kimfetch/color"
+		fi
+	
+		echo "$color_code" > "$HOME/.config/kimfetch/color"
+	else
+		echo "Invalid color option"
+		exit 0
+	fi
+fi
+# Check if pre-existing color is set or not. Use default if not.
+if [ ! -e "$HOME/.config/kimfetch/color" ]; then
+	# Default:
+	# Red for Red Star OS 2.0
+	# Green for Red Star OS 3.0
+	if [[ ${OSSTR} == *"2"* ]]; then
+		COLOR="\e[31m"
+	elif [[ ${OSSTR} == *"3"* ]]; then
+		COLOR="\e[32m"
+	else
+		COLOR="\e[31m"
+	fi
+else
+	if [ "$(cat $HOME/.config/kimfetch/color)" == "1" ]; then
+		COLOR="\e[31m"
+	fi
+	if [ "$(cat $HOME/.config/kimfetch/color)" == "2" ]; then
+		COLOR="\e[32m"
+	fi
+fi
+# Check if user cancelled color with -f flag
+if [[ -n "$default_color" ]] && [ "$default_color" == true ]; then
+	# Make sure user is not running as root
+	if [ "$EUID" -eq 0 ]; then
+		echo "Error: Must run as non-root"
+		newline
+		exit 1
+	fi
+	if [ ! -e "$HOME/.config/kimfetch/color" ] && [ ! -d "$HOME/.config/kimfetch" ]; then
+		echo "Color already on default"
+	fi
+	rm "$HOME/.config/kimfetch"
+	rmdir "$HOME/.config/kimfetch"
+fi
+
+# === Header ===
+# "Username@Hostname" as displayed on each prompt
+SESSION="${COLOR}$(whoami)\e[0m@${COLOR}$(hostname)\e[0m";
+
+# === Separation line below header ===
+SEP=""
+LOOP="${#SESSION}"
+LOOP=$(($LOOP-16-10)) # Do not count color codes. Remove two "\e[1;3Xm" and two "\e[0m"
+SEP=$(printf "%0.s-" $(seq 1 $LOOP))
+
 printf "\
-\e[1;31m                      ..                      \e[0m $(printf $SESSION)
-\e[1;31m                    .oK0l                     \e[0m $(printf -- $SEP) 
-\e[1;31m                   :0KKKKd.                   \e[0m $(printf "\e[1;31mOS\e[0m: $OS")
-\e[1;31m                 .xKO0KKKKd                   \e[0m $(printf "\e[1;31mHost\e[0m: $BOARD")
-\e[1;31m                ,Od' .d0000l                  \e[0m $(printf "\e[1;31mKernel\e[0m: $KERNEL")
-\e[1;31m               .c;.   .'''...           ..'.  \e[0m $(printf "\e[1;31mShell\e[0m: $PROFILE_SHELL $PROFILE_SHELL_VER")
-\e[1;31m  .,:cloddxxxkkkkOOOOkkkkkkkkxxxxxxxxxkkkx:   \e[0m $(printf "\e[1;31mResolution\e[0m: $SCREEN")
-\e[1;31m  ;kOOOOOOOkxOkc'...',;;;;,,,'',;;:cllc:,.    \e[0m $(printf "\e[1;31mDE\e[0m: $DE")
-\e[1;31m   .okkkkd,.lko  .......',;:cllc:;,,'''''.    \e[0m $(printf "\e[1;31mWM\e[0m: $WM")
-\e[1;31m     .cdo. :xd' cd:.  ..';'',,,'',,;;;,'.     \e[0m $(printf "\e[1;31mTerminal\e[0m: $TER")
-\e[1;31m        . .ddl.;doooc'..;oc;'..';::;,'.       \e[0m $(printf "\e[1;31mCPU\e[0m: $CPU")
-\e[1;31m          coo;.oooolllllllcccc:'.  .          \e[0m $(printf "\e[1;31mGPU\e[0m: $GPU")
-\e[1;31m         .ool''lllllccccccc:::::;.            \e[0m $(printf "\e[1;31mMemory\e[0m: $MEM")
-\e[1;31m         ;lll. .':cccc:::::::;;;;'            \e[0m $(printf "\e[1;31mStorage\e[0m: $STO")
-\e[1;31m         :lcc:'',..';::::;;;;;;;,,.           \e[0m 
-\e[1;31m         :cccc::::;...';;;;;,,,,,,.           \e[0m \e[30m███\e[31m███\e[32m███\e[33m███\e[34m███\e[35m███\e[36m███\e[37m███
-\e[1;31m         ,::::::;;;,'.  ..',,,,'''.           \e[0m \e[1;30m███\e[1;31m███\e[1;32m███\e[1;33m███\e[1;34m███\e[1;35m███\e[1;36m███\e[1;37m███
-\e[1;31m          ........          ......            \e[0m
+$COLOR                      ..                      \e[0m $(printf $SESSION)
+$COLOR                    .oK0l                     \e[0m $(printf -- $SEP) 
+$COLOR                   :0KKKKd.                   \e[0m $(printf "${COLOR}OS\e[0m: $OS")
+$COLOR                 .xKO0KKKKd                   \e[0m $(printf "${COLOR}Host\e[0m: $BOARD")
+$COLOR                ,Od' .d0000l                  \e[0m $(printf "${COLOR}Kernel\e[0m: $KERNEL")
+$COLOR               .c;.   .'''...           ..'.  \e[0m $(printf "${COLOR}Shell\e[0m: $PROFILE_SHELL $PROFILE_SHELL_VER")
+$COLOR  .,:cloddxxxkkkkOOOOkkkkkkkkxxxxxxxxxkkkx:   \e[0m $(printf "${COLOR}Resolution\e[0m: $SCREEN $FPS")
+$COLOR  ;kOOOOOOOkxOkc'...',;;;;,,,'',;;:cllc:,.    \e[0m $(printf "${COLOR}DE\e[0m: $DE")
+$COLOR   .okkkkd,.lko  .......',;:cllc:;,,'''''.    \e[0m $(printf "${COLOR}WM\e[0m: $WM")
+$COLOR     .cdo. :xd' cd:.  ..';'',,,'',,;;;,'.     \e[0m $(printf "${COLOR}Terminal\e[0m: $TER")
+$COLOR        . .ddl.;doooc'..;oc;'..';::;,'.       \e[0m $(printf "${COLOR}CPU\e[0m: $CPU")
+$COLOR          coo;.oooolllllllcccc:'.  .          \e[0m $(printf "${COLOR}GPU\e[0m: $GPU")
+$COLOR         .ool''lllllccccccc:::::;.            \e[0m $(printf "${COLOR}Memory\e[0m: $MEM")
+$COLOR         ;lll. .':cccc:::::::;;;;'            \e[0m $(printf "${COLOR}Storage\e[0m: $STO")
+$COLOR         :lcc:'',..';::::;;;;;;;,,.           \e[0m 
+$COLOR         :cccc::::;...';;;;;,,,,,,.           \e[0m \e[30m███\e[31m███\e[32m███\e[33m███\e[34m███\e[35m███\e[36m███\e[37m███
+$COLOR         ,::::::;;;,'.  ..',,,,'''.           \e[0m \e[1;30m███\e[1;31m███\e[1;32m███\e[1;33m███\e[1;34m███\e[1;35m███\e[1;36m███\e[1;37m███
+$COLOR          ........          ......            \e[0m
 "
